# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      HEROKU_APP_NAME: "hanif-maleki"

    steps:
      - checkout
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run: ls -all
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: ls -all
      - setup_remote_docker
      - run: ls -all
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build Project
          cpmmand: gradle build -xtest

      # run tests!
      - run:
          name: Test the Project
          command: gradle test

      # Create Docker Image
      - run:
          name: Build application Docker image
          command: |
            docker build --build-arg JAR_FILE=build/libs/*.jar -t springio/gs-spring-boot-docker .

#      - run: heroku container:push web -a $HEROKU_APP_NAME
#      - run: heroku container:release web -a $HEROKU_APP_NAME

  deploy:
    #    executor: heroku/default
    machine:
      image: ubuntu-1604:201903-01
    environment:
      HEROKU_APP_NAME: "hanif-maleki"
    #      HEROKU_API_KEY: "$HEROKU_API_KEY"
    steps:
      - run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: heroku version
      - run: HEROKU_DEBUG=true HEROKU_DEBUG_HEADERS=1 heroku apps
      - checkout
      #        - heroku/deploy-via-git
      #        - heroku/push-docker-image
      #            process-types: web
      #      - run: sudo heroku container:login
      - run: heroku container:push web -a $HEROKU_APP_NAME
      - run: heroku container:release web -a $HEROKU_APP_NAME
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: Heroku
#      - deploy:
#          requires:
#            - build
#          context: Heroku